version: "3"
services:
  app:
    build:
      context: ./app
      args:
        NODE_ENV: development
        DB_HOST: postgres
        DB_DATABASE: tokyomap
        DB_USER: docker
        DB_PASSWORD: docker
        COOKIE_SECRET_KEY: hoge
        DOMAIN_API: https://localhost/api
        DOMAIN_WEB: https://localhost
        REDIS_ENDPOINT: redis
        PORT: 4000
    image: tokyomap.app:dev
    container_name: tokyomap-app
    ports:
      - "4000:4000"
    env_file: ./app/.dev.env
    command:  [sh, -c, yarn start]
