version: "3"
services:
    app:
        build:
            context: ./app # the dir the Dockerfile is in
            args:
                NODE_ENV: "development"
                DB_HOST=: "db"
                DB_USER: "docker"
                DB_PASSWORD: "docker"
                DB_DATABASE: "tokyomap_api"
        image: tokyomap.api/app:dev # image name
        container_name: tokyomap.api-app
        ports:
            - "4000:4000"
        volumes:
            - "./app:/src"
        env_file: ./app/.env
        command:  [sh, -c, yarn install && yarn start]
    web:
        build:
            context: ./web
        image: tokyomap.api/web:dev
        container_name: tokyomap.api-web
        ports:
            - "80:80"
    db:
        image: mariadb/server
        container_name: tokyomap.api-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tokyomap_api
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./db/var:/var/lib/mysql
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf # config
            - ./db/sql:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
