version: "3"
services:
    app:
        build:
            context: ./app
            args:
                NODE_ENV: development
                DB_HOST: db
                DB_USER: docker
                DB_PASSWORD: docker
                DB_DATABASE: tokyomap_api
                COOKIE_SECRET_KEY: hoge
                DOMAIN_API: http://localhost/api
                DOMAIN_CLIENT: http://localhost
                REDIS_ENDPOINT: redis
                PORT: 4000
        image: tokyomap.api/app:dev
        container_name: tokyomap.api-app
        ports:
            - "4000:4000"
        env_file: ./app/.env
        command:  [sh, -c, yarn start]
    db:
        image: mariadb/server
        container_name: tokyomap.api-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tokyomap_api
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: Asia/Tokyo
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./db/var:/var/lib/mysql
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf # config
            - ./db/sql:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
    redis:
        image: "redis:latest"
        container_name: tokyomap.api-redis
        volumes:
            - "./redis/data:/data"
        ports:
            - "6379:6379"
    web:
        build:
            context: ./web
        container_name: tokyomap.api-web
        volumes:
          - "./web/public:/usr/share/nginx"
        ports:
            - "80:80"
            # - "444:443"
