USE tokyomap_api;

/* create tables */
START TRANSACTION;
DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
    post_no INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    post_text VARCHAR(256) NOT NULL,
    post_name INT(5) UNSIGNED NOT NULL,
    posted_at DATETIME NOT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin ENGINE=InnoDB;
COMMIT;
