USE tokyomap_api;

/* create tables */
START TRANSACTION;
DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
    no INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    message VARCHAR(256) NOT NULL,
    user VARCHAR(256) NOT NULL,
    posted_at DATETIME NOT NULL,
    lat DECIMAL(10, 7) NOT NULL,
    lng DECIMAL(10, 7) NOT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin ENGINE=InnoDB;
COMMIT;
