USE tokyomap;

START TRANSACTION;
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    user_id VARCHAR(128) UNIQUE NOT NULL,
    user_name VARCHAR(128) NOT NULL,
    profile_image_url VARCHAR(256)
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin ENGINE=InnoDB;
COMMIT;

START TRANSACTION;
DROP TABLE IF EXISTS tweets;
CREATE TABLE tweets (
    tweet_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    message VARCHAR(255) NOT NULL,
    posted_at DATETIME NOT NULL,
    disappear_at DATETIME NOT NULL,
    lat DECIMAL(21, 18) NOT NULL,
    lng DECIMAL(21, 18) NOT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin ENGINE=InnoDB;
ALTER TABLE tweets ADD FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;
COMMIT;
